### ISSUE TITLE
Question: factor out zio3d/core to separate wrapper library?

### ISSUE THREAD

**Issue by bbarker** [wongelz/zio3d#2]
Hi! 

I was excited to find this project as a guide to updating an old project I was working on. I wonder if factoring out the zio3d/core code to a project might be beneficial? In any case, I can plan to just use the code as-is for now, so no worries.

**Comment by wongelz** [comment]
@bbarker Yes, if you (or others) want to re-use the core to build different games then that would certainly be beneficial. However it currently doesn't cover the entire OpenGL/LWJGL API (I've only been adding the bare-minimum functions for my demo) so you may want to take this into consideration.
